### ISSUE TITLE
Make posting comments work with "internal" or "private" repos.

### ISSUE THREAD

**Issue by ImpossibleShape** [cpp-linter/cpp-linter-action#142]

**Comment by 2bndy5** [comment]
Much like your screenname, this was tried and ended up being impossible because we need better docs from Github's REST API. If we were to support this, then you'd see multiple comments posted in the thread (👎🏼).

It is currently disabled for private repos because [`file-annotations`](https://github.com/cpp-linter/cpp-linter-action#file-annotations) can alternatively be used instead of [`thread-comments`](https://github.com/cpp-linter/cpp-linter-action#thread-comments).

Not sure what you mean by "internal", but you can enable analysis for git submodules via the [`ignore`](https://github.com/cpp-linter/cpp-linter-action#ignore) option.
```yml
ignore: '!submodule/path'
```

**Comment by ImpossibleShape** [comment]
internal is a type of repo for "Enterprise" customers. It's basically inside the org it's public, but external to the org it's private. For all practical purposes you treat them like private.

**Comment by 2bndy5** [comment]
Oh. That's news to me. Thanks!
