### ISSUE TITLE
.clang-tidy is not considered

### ISSUE THREAD

**Issue by ivancho-ifa** [cpp-linter/cpp-linter-action#156]
I have a `.clang-tidy` configuration in my project https://github.com/ivancho-ifa/figures-counter however it doesn't seem to respect the specified checks. 

https://github.com/ivancho-ifa/figures-counter/commit/e18b642b8c99fe5b33fc32d5538fc5f757d5fee7#annotation_12023133572

I've disabled the -modernize-use-trailing-return-type check but I still receive warnings for it. This works locally

**Comment by 2bndy5** [comment]
Strange. The CI logs show:
> ```
> Running "clang-tidy.exe --export-fixes=.cpp-linter_cache\clang_tidy_output.yml -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-* -p D:\a\figures-counter\figures-counter\out\build\x64-debug --extra-arg= figures-counter/impl/internal/sequential_figures_counter.cpp"
> ```

I find the `--extra-arg=` interesting since it shouldn't be there if there wasn't any extra args set.

There is no indication that the .clang-tidy file was found or not. That is typical for clang-tidy output though.

I did notice that you didn't turn off the default check overrides though:
> ```
> -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*
> ```
To rely solely on the .clang-tidy file, set the action's [`tidy-checks`](https://github.com/cpp-linter/cpp-linter-action#tidy-checks) to an empty string:
```yml
      with:
        tidy-checks: ''
```

**Comment by ivancho-ifa** [comment]
Thank you! This fixed my issue. I didn't notice the default overrides.
