### ISSUE TITLE
Display example screenshots on the documentation site

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#268]
### Describe the behavior you would like

Right now I can see the screenshots in README https://github.com/cpp-linter/cpp-linter-action?tab=readme-ov-file#example

If possible to display the example screenshot on the documentation site https://cpp-linter.github.io/cpp-linter-action? that would be convenient for users when they view the documentation.

Then we might remove the examples section from README to keep it simple, and also let the user focus on one place, either the documentation site or the README.

**Comment by 2bndy5** [comment]
I'm a little confused. Did you want to remove them from the repo README?

I made it so they display on both because, in my experience, not many people read the docs for whatever reason. Maybe they
- don't see the various links
- they are just turned off by a lot of words (and no pictures)
- mouse is broken?! (I don't really know why people do what they do)
 
In general, people are just lazy. They 
1. click a link
2. scroll the page for pictures or code examples
3. go back to search if nothing grabbed their attention

**Comment by 2bndy5** [comment]
> Maybe the "What's New" section is useless and can be removed?

It is rather outdated. I'd prefer a proper changelog, so we wouldn't need to spend time updating a "What's New" section.
