### ISSUE TITLE
Enable `tidy-review` and `format-review` for draft PRs

### ISSUE THREAD

**Issue by ralfkonrad** [cpp-linter/cpp-linter-action#270]
### Is your idea related to an existing feature?

tidy-review, format-review

### Describe the behavior you would like

Perhaps I missed somethings but it looks like `tidy-review` and `format-review` are not supported in draft PRs. At least, there are no code reviews available in a draft PR even with the features enabled.

We are using drafts a lot for early reviews and the other obvious reasons, so it would be good to be able to incorporate the suggested changes already at that stage.

### Additional context

Otherwise, it's really good action. Thanks for the effort!

**Comment by 2bndy5** [comment]
> Perhaps I missed somethings but it looks like tidy-review and format-review are not supported in draft PRs.

This was intentional. The [tidy-review](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#tidy-review) feature is still a bit experimental from our end. And, `format-review` is less complicated to implement.

I would say you missed this if you didn't read [our documented PR review caveats](https://cpp-linter.github.io/cpp-linter-action/pr-review-caveats/).


This actually marks the second request to allow drafted PRs to be reviewed by cpp-linter. Maybe I should expose this capability via an env car (`CPP_LINTER_REVIEW_DRAFTS=1` perhaps).

Is be more confident in these features if I could devise a way to reduce duplicate suggestions...

**Comment by ralfkonrad** [comment]
> I would say you missed this if you didn't read [our documented PR review caveats](https://cpp-linter.github.io/cpp-linter-action/pr-review-caveats/).

True, sorry for that. I only searched in [Inputs and Outputs](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/) for "draft".

And thanks for your quick answer. I guess it might be enough for the time being to look at the `thread-comments` and `file-annotations` to resolve any issue "manually". Normally, for `clang-format` it is the forgotten formatting before saving in the IDE anyhow.

Feel free to close this feature request or keep it open for others as reference.

**Comment by 2bndy5** [comment]
I'll close it as "unplanned" and pin it for visibility. People that way this feature can add a 👍. This thread will not be locked either, so anyone with additional context can post it here.
