### ISSUE TITLE
Post duplicate annotations when run action again

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#58]
I noticed when the same actions run again, the annotations also are posted again. @2bndy5  If possible not send duplicate annotations?

The test example is here: https://github.com/shenxianpeng/test-cpp-linter-action/pull/17/files

**Comment by 2bndy5** [comment]
I noticed this too when testing all the supported version of clang-tools with a workflow matrix. We're not actually using the REST API to make annotations, rather we're using github workflow log commands.

We could remove duplicate annotations if we use the REST API, but it isn't exactly the same as removing duplicate thread comments. I'm not sure if we can sneak in a HTML comment like we do for thread comments. If I recall correctly, the annotations' author is the workflow run count (or something similar), not a generic constant bot ID number. As far as I know, there isn't a workflow log command that allows removing annotations.

I'm not too concerned about duplicate annotations because why would anyone run the same action more than once on the same file(s)? Can you think of a use case for this (other than our own development purposes)?

**Comment by 2bndy5** [comment]
We could throw in an option to disable annotations like the `thread-comments` option. This seems more viable

**Comment by shenxianpeng** [comment]
> Can you think of a use case for this (other than our own development purposes)?

I used the default configuration as follows. when I push, it will add annotations, when I create PR, it will add annotations again.

```yaml
on:
  push:
    paths-ignore: "docs/**"
  pull_request:
    paths-ignore: "docs/**"
```

**Comment by shenxianpeng** [comment]
> We could throw in an option to disable annotations like the thread-comments option. This seems more viable

Yes, it's good to support disabled annotations. I prefer to use annotations instead of comments, so it should be best if this problem could be solved.

**Comment by 2bndy5** [comment]
oh, that could be solved by configuring the workflow to execute the action only when a PR is opened or synchronized (specifically not when closed).
```yml
on:
  pull_request:
    types: [opened, synchronize, reopened]  # default includes `closed` event
```

**Comment by 2bndy5** [comment]
ok I'll add the option to disable the annotations; it should be rather easy.

**Comment by shenxianpeng** [comment]
Yes, if only one event is configured, that won't happen. so the example in README may also need to be updated.
