### ISSUE TITLE
Need support android cross compile

### ISSUE THREAD

**Issue by PatriceJiang** [cpp-linter/cpp-linter-action#62]
The docker env is not complete for android, and compile parameters in `compile_commands.json` are broken.

**Comment by 2bndy5** [comment]
>docker env is not complete for android

Correct. Not sure what to suggest for this because there's more than 1 way to cross-compile for android, and I'm assuming you're CI is running on Ubuntu. This action can also be run as a python executable, so you don't need to rely on the docker env to set things up for you, See the [example about using a windows runner in the README](https://github.com/cpp-linter/cpp-linter-action#using-a-windows-based-runner).

> compile parameters in `commands.json` are broken

Can you link a project that better describes what this means? I assume it has to do with using compiler-specific flags, so it might be better to setup up the build env on your own and run this action as a python executable.

**Comment by PatriceJiang** [comment]
Thanks for your reply.

> This action can also be run as a python executable

This may solve both issues. 

When using docker, since the filesystem is changed, the include path becomes invalid.

**Comment by PatriceJiang** [comment]
I am wonder that since the env of the docker is different from the env which generate `compile_commands.json`, how can it work for most cases?

**Comment by 2bndy5** [comment]
It works by using the system default compiler with the set of std libs, but I suspect projects that build against other non-std libs must roll their own build env instead of using the limited convenience of the docker env.

There may be way to properly include libs from the runner file system when using the docker's env, but the setup time is significantly better when (in my experience) not using the docker env.
